services:
  - type: web
    name: pulsepair-chat
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "daphne -b 0.0.0.0 -p $PORT config.asgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CSRF_TRUSTED_ORIGINS
        value: https://acny.onrender.com
      - key: APP_PREFIX
        value: e2e_chat
      - key: USE_MANIFEST_STATIC
        value: False
      - key: MONGODB_URI
        value: mongodb+srv://nishantbaruah3_db_user:LptzrluHQSRJmhFC@cluster1.fc5ufaf.mongodb.net/?appName=cluster1
      - key: MONGODB_DB_NAME
        value: pulsepair_chat
      - key: SECRET_KEY
        generateValue: true
